### ISSUE TITLE
Support Identity v3

### ISSUE THREAD

**Issue by stenstad** [tulios/nightcrawler_swift#34]
Hi!

Since the release of Openstack Havana the preferred version of Identity to use is v3. Some cloud providers have now migrated to only supporting v3 for token generation to get support for domains.

Currently the Nightcrawler Swift does not work with providers that require support for Identity v3.

Would it be possible to add support for Identity v3 in this project as well?

**Comment by tulios** [comment]
@ggarnier

**Comment by stenstad** [comment]
If you need some credentials to test your implementation with, I can provide that.
