### ISSUE TITLE
[Ruby 2.3] Thread.exclusive is deprecated, use Mutex

### ISSUE THREAD

**Issue by emerleite** [tulios/nightcrawler_swift#35]
I guess we should fix this. It's related with **multi_mime** gem, and they not have a newer version. The last one is the version we're using - https://rubygems.org/gems/multi_mime

I created a related issue here: https://github.com/karlfreeman/multi_mime/issues/5

**Comment by tulios** [comment]
Nice! We can patch `multi_mime` here if needed.

**Comment by tulios** [comment]
I can create a pull-request to `multi_mime` with the fix, it's a small method (https://github.com/karlfreeman/multi_mime/blob/e10f41a347c9137dd2a97657e6b7dc09ae7101c1/lib/multi_mime.rb#L48) and we can patch it here while they accept the PR. The project is not being updated for 2 years, thus it might take a while.

**Comment by tulios** [comment]
The gem was updated (https://rubygems.org/gems/multi_mime/versions/1.1.0), now it's our turn
